### Importing Libraries

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics._regression import mean_absolute_error, mean_squared_error, root_mean_squared_error

In [2]:
df = pd.read_csv( '../data/raw/Parkinsson disease.csv')

In [3]:
df.drop( columns = 'name', inplace= True )

In [4]:
df

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,0.426,...,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,0.626,...,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,0.482,...,0.08270,0.01309,20.651,1,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,0.517,...,0.08771,0.01353,20.644,1,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,0.584,...,0.10470,0.01767,19.649,1,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,174.188,230.978,94.261,0.00459,0.00003,0.00263,0.00259,0.00790,0.04087,0.405,...,0.07008,0.02764,19.517,0,0.448439,0.657899,-6.538586,0.121952,2.657476,0.133050
191,209.516,253.017,89.488,0.00564,0.00003,0.00331,0.00292,0.00994,0.02751,0.263,...,0.04812,0.01810,19.147,0,0.431674,0.683244,-6.195325,0.129303,2.784312,0.168895
192,174.688,240.005,74.287,0.01360,0.00008,0.00624,0.00564,0.01873,0.02308,0.256,...,0.03804,0.10715,17.883,0,0.407567,0.655683,-6.787197,0.158453,2.679772,0.131728
193,198.764,396.961,74.904,0.00740,0.00004,0.00370,0.00390,0.01109,0.02296,0.241,...,0.03794,0.07223,19.020,0,0.451221,0.643956,-6.744577,0.207454,2.138608,0.123306
194,214.289,260.277,77.973,0.00567,0.00003,0.00295,0.00317,0.00885,0.01884,0.190,...,0.03078,0.04398,21.209,0,0.462803,0.664357,-5.724056,0.190667,2.555477,0.148569

In [5]:
df.sample()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
97,125.036,143.946,116.187,0.0128,0.0001,0.00743,0.00623,0.02228,0.03886,0.342,...,0.06406,0.08151,15.338,1,0.629574,0.714485,-4.020042,0.265315,2.671825,0.340623

In [6]:
df.columns

Index(['MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Jitter(%)',
       'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ', 'Jitter:DDP',
       'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'status', 'RPDE', 'DFA',
       'spread1', 'spread2', 'D2', 'PPE'],
      dtype='object')

## Split features into X & y

In [7]:
X = df.drop( columns = 'status' )
y = df['status']

In [8]:
X.shape

(195, 22)

## Split into training & testing

In [9]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [87]:
X_train

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
5,120.552,131.162,113.787,0.00968,0.00008,0.00463,0.00750,0.01388,0.04701,0.456,0.02328,0.03526,0.03243,0.06985,0.01222,21.378,0.415564,0.825069,-4.242867,0.299111,2.187560,0.357775
135,110.453,127.611,105.554,0.00494,0.00004,0.00244,0.00315,0.00731,0.04128,0.379,0.02229,0.02592,0.03316,0.06688,0.02529,17.707,0.653427,0.706687,-5.333619,0.322044,2.631793,0.228319
122,138.190,203.522,83.340,0.00704,0.00005,0.00406,0.00398,0.01218,0.04479,0.441,0.02587,0.02567,0.03220,0.07761,0.01968,18.305,0.538016,0.741480,-5.418787,0.160267,2.090438,0.229892
167,260.105,264.919,237.303,0.00339,0.00001,0.00205,0.00186,0.00616,0.02030,0.197,0.01186,0.01230,0.01367,0.03557,0.00910,21.083,0.440988,0.628058,-7.517934,0.160414,1.881767,0.075587
85,180.978,200.125,155.495,0.00406,0.00002,0.00220,0.00244,0.00659,0.03852,0.331,0.02107,0.02493,0.02877,0.06321,0.02782,16.176,0.583574,0.727747,-5.657899,0.315903,3.098256,0.200423
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,155.078,163.736,144.148,0.00168,0.00001,0.00068,0.00092,0.00204,0.01064,0.097,0.00522,0.00632,0.00928,0.01567,0.00233,29.746,0.334171,0.677930,-6.981201,0.184550,2.129924,0.106802
14,152.845,163.305,75.836,0.00294,0.00002,0.00121,0.00149,0.00364,0.01828,0.158,0.01064,0.00972,0.01246,0.03191,0.00609,24.922,0.474791,0.654027,-6.105098,0.203653,2.125618,0.170100
92,148.272,164.989,142.299,0.00459,0.00003,0.00250,0.00256,0.00750,0.04190,0.383,0.02383,0.02521,0.03051,0.07150,0.01914,18.780,0.454444,0.734504,-5.952058,0.087840,2.344336,0.186489
179,148.143,155.982,135.041,0.00392,0.00003,0.00204,0.00231,0.00612,0.01450,0.131,0.00725,0.00876,0.01263,0.02175,0.00540,23.683,0.398499,0.778349,-5.711205,0.240875,2.845109,0.192730
102,139.224,586.567,66.157,0.03011,0.00022,0.01854,0.01628,0.05563,0.09419,0.930,0.05551,0.05005,0.06023,0.16654,0.25930,10.489,0.596362,0.641418,-3.269487,0.270641,2.690917,0.444774

In [88]:
y_train

5      1
135    1
122    1
167    0
85     1
      ..
106    1
14     1
92     1
179    1
102    1
Name: status, Length: 156, dtype: int64

# Model Selection

### Ensemble models

In [10]:
knn_model = KNeighborsRegressor( n_neighbors= 1 )

In [11]:
X_train.shape

(156, 22)

In [12]:
X_test.shape

(39, 22)

In [13]:
y_test.shape

(39,)

In [14]:
y_test

138    1
16     1
155    1
96     1
68     1
153    1
55     1
15     1
112    1
111    1
184    0
18     1
82     1
9      1
164    1
117    1
69     1
113    1
192    0
119    1
123    1
144    1
66     1
45     0
158    1
115    1
67     1
93     1
30     0
101    1
118    1
75     1
24     1
172    0
127    1
169    0
19     1
168    0
73     1
Name: status, dtype: int64

In [15]:
knn_model.fit( X_train, y_train )

KNeighborsRegressor(n_neighbors=1)

In [89]:
y_pred_train = knn_model.predict( X_train )
y_pred_train[:5]

array([0.71428571, 1.        , 1.        , 0.        , 1.        ])

In [90]:
y_pred_test = knn_model.predict( X_test )

In [96]:
pd.DataFrame({
    'Actual' : y_test[20:35],
    'Predicted' : y_pred_test[20:35],
    'Residuals' : y_test[20:35] - y_pred_test[20:35]
})

     Actual  Predicted  Residuals
123       1   1.000000   0.000000
144       1   1.000000   0.000000
66        1   1.000000   0.000000
45        0   0.000000   0.000000
158       1   0.857143   0.142857
115       1   0.571429   0.428571
67        1   1.000000   0.000000
93        1   1.000000   0.000000
30        0   0.285714  -0.285714
101       1   1.000000   0.000000
118       1   0.571429   0.428571
75        1   0.714286   0.285714
24        1   1.000000   0.000000
172       0   0.428571  -0.428571
127       1   1.000000   0.000000

## metrics

### MAE ( Mean Absolute Error ) ->  Look on the Avg. Error
### MSE ( Mean Squared Error )  ->  Triggers if there is high residuals (differences)
### RMSE ( Root Mean Squared Error ) -> Error between MAE & MSE

In [98]:
MAE_train = mean_absolute_error( y_train, y_pred_train )
MAE_test = mean_absolute_error( y_test, y_pred_test )

MSE_train = mean_squared_error( y_train, y_pred_train )
MSE_test = mean_squared_error( y_test, y_pred_test )

RMSE_train = root_mean_squared_error( y_train, y_pred_train )
RMSE_test = root_mean_squared_error( y_test, y_pred_test )

print( f'Mean Absolute Error of training : { MAE_train }' )
print( f'Mean Absolute Error of Testing : { MAE_test }' )
print(  )
print( f'Mean Squared Error of training : { MSE_train }' )
print( f'Mean Squared Error of Testing : { MSE_test }' )
print(  )
print( f'Root Mean Squared Error of Training : { RMSE_train }' )
print( f'Root Mean Squared Error of Testing : { RMSE_test }' )

Mean Absolute Error of training : 0.16666666666666666
Mean Absolute Error of Testing : 0.24542124542124547

Mean Squared Error of training : 0.07692307692307693
Mean Squared Error of Testing : 0.1564625850340136

Root Mean Squared Error of Training : 0.2773500981126146
Root Mean Squared Error of Testing : 0.3955535172818131

### Evaluation of previous n_neighbors = 5
**9.4, 136, 11.6**

### Calc. Cross Validation Score

In [99]:
cross_val_score( knn_model, X_train, y_train, cv= 4, scoring='neg_mean_squared_error').mean()

np.float64(-0.11983254840397696)

In [100]:
pd.set_option( 'display.max_columns', None)

In [101]:
X_train.sample()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
116,158.219,442.557,71.948,0.00476,0.00003,0.00214,0.00207,0.00642,0.01458,0.148,0.00606,0.00747,0.01312,0.01818,0.01554,26.356,0.450798,0.653823,-6.051233,0.27328,2.640798,0.170106

## Curse of Dimensiality

## Fine Tuning

# Testing

In [102]:
df.sample()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,MDVP:APQ,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
168,197.569,217.627,90.794,0.00803,0.00004,0.0049,0.00448,0.0147,0.02177,0.189,0.01279,0.01272,0.01439,0.03836,0.01337,19.269,0,0.372222,0.725216,-5.736781,0.164529,2.88245,0.202879

## Testing GridSearchCV on KNN Model

In [103]:
knn_model = KNeighborsRegressor(  )

In [104]:
gs_knn =  GridSearchCV(
    estimator= knn_model,
    param_grid= { 'n_neighbors' : [ 2, 3, 4, 5, 6, 7 ] }
)

In [105]:
gs_knn.fit( X_train, y_train )

GridSearchCV(estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': [2, 3, 4, 5, 6, 7]})

In [106]:
gs_knn.best_params_

{'n_neighbors': 2}

In [108]:
y_pred_test

array([0.85714286, 0.57142857, 1.        , 1.        , 1.        ,
       0.85714286, 0.85714286, 1.        , 0.14285714, 0.14285714,
       0.85714286, 1.        , 1.        , 1.        , 0.85714286,
       0.57142857, 1.        , 0.14285714, 0.85714286, 0.42857143,
       1.        , 1.        , 1.        , 0.        , 0.85714286,
       0.57142857, 1.        , 1.        , 0.28571429, 1.        ,
       0.57142857, 0.71428571, 1.        , 0.42857143, 1.        ,
       0.        , 1.        , 0.85714286, 0.57142857])

In [109]:
knn_comparison_df = pd.DataFrame({
    'Actual (True)' : y_test,
    'Predicted (KNN)' : y_pred_test,
    'Residuals' : np.abs( y_test- y_pred_test )
})
knn_comparison_df

     Actual (True)  Predicted (KNN)  Residuals
138              1         0.857143   0.142857
16               1         0.571429   0.428571
155              1         1.000000   0.000000
96               1         1.000000   0.000000
68               1         1.000000   0.000000
153              1         0.857143   0.142857
55               1         0.857143   0.142857
15               1         1.000000   0.000000
112              1         0.142857   0.857143
111              1         0.142857   0.857143
184              0         0.857143   0.857143
18               1         1.000000   0.000000
82               1         1.000000   0.000000
9                1         1.000000   0.000000
164              1         0.857143   0.142857
117              1         0.571429   0.428571
69               1         1.000000   0.000000
113              1         0.142857   0.857143
192              0         0.857143   0.857143
119              1         0.428571   0.571429
123              1         1.000000   0.000000
144              1         1.000000   0.000000
66               1         1.000000   0.000000
45               0         0.000000   0.000000
158              1         0.857143   0.142857
115              1         0.571429   0.428571
67               1         1.000000   0.000000
93               1         1.000000   0.000000
30               0         0.285714   0.285714
101              1         1.000000   0.000000
118              1         0.571429   0.428571
75               1         0.714286   0.285714
24               1         1.000000   0.000000
172              0         0.428571   0.428571
127              1         1.000000   0.000000
169              0         0.000000   0.000000
19               1         1.000000   0.000000
168              0         0.857143   0.857143
73               1         0.571429   0.428571

In [110]:
knn_comparison_df

     Actual (True)  Predicted (KNN)  Residuals
138              1         0.857143   0.142857
16               1         0.571429   0.428571
155              1         1.000000   0.000000
96               1         1.000000   0.000000
68               1         1.000000   0.000000
153              1         0.857143   0.142857
55               1         0.857143   0.142857
15               1         1.000000   0.000000
112              1         0.142857   0.857143
111              1         0.142857   0.857143
184              0         0.857143   0.857143
18               1         1.000000   0.000000
82               1         1.000000   0.000000
9                1         1.000000   0.000000
164              1         0.857143   0.142857
117              1         0.571429   0.428571
69               1         1.000000   0.000000
113              1         0.142857   0.857143
192              0         0.857143   0.857143
119              1         0.428571   0.571429
123              1         1.000000   0.000000
144              1         1.000000   0.000000
66               1         1.000000   0.000000
45               0         0.000000   0.000000
158              1         0.857143   0.142857
115              1         0.571429   0.428571
67               1         1.000000   0.000000
93               1         1.000000   0.000000
30               0         0.285714   0.285714
101              1         1.000000   0.000000
118              1         0.571429   0.428571
75               1         0.714286   0.285714
24               1         1.000000   0.000000
172              0         0.428571   0.428571
127              1         1.000000   0.000000
169              0         0.000000   0.000000
19               1         1.000000   0.000000
168              0         0.857143   0.857143
73               1         0.571429   0.428571

## Visualize Residuals

In [111]:
px.line( knn_comparison_df.head( 25 ), x  = ['Actual (True)', 'Predicted (KNN)'] )

In [112]:
knn_comparison_df.head( 25 )

     Actual (True)  Predicted (KNN)  Residuals
138              1         0.857143   0.142857
16               1         0.571429   0.428571
155              1         1.000000   0.000000
96               1         1.000000   0.000000
68               1         1.000000   0.000000
153              1         0.857143   0.142857
55               1         0.857143   0.142857
15               1         1.000000   0.000000
112              1         0.142857   0.857143
111              1         0.142857   0.857143
184              0         0.857143   0.857143
18               1         1.000000   0.000000
82               1         1.000000   0.000000
9                1         1.000000   0.000000
164              1         0.857143   0.142857
117              1         0.571429   0.428571
69               1         1.000000   0.000000
113              1         0.142857   0.857143
192              0         0.857143   0.857143
119              1         0.428571   0.571429
123              1         1.000000   0.000000
144              1         1.000000   0.000000
66               1         1.000000   0.000000
45               0         0.000000   0.000000
158              1         0.857143   0.142857

In [113]:
px.histogram( knn_comparison_df, x  = ['Actual (True)', 'Predicted (KNN)'] )

<hr>

# [2] Linear Regression

In [114]:
from sklearn.linear_model import LinearRegression

In [115]:
lin_reg_model = LinearRegression()

In [116]:
os.cpu_count()

4

In [117]:
lin_reg_model.fit( X_train, y_train )

LinearRegression()

In [118]:
y_pred_train_lr = lin_reg_model.predict( X_train )
y_pred_test_lr = lin_reg_model.predict( X_test )

In [119]:
y_pred_train_lr

array([ 0.96610436,  0.96015574,  0.96850389,  0.06135241,  0.88816275,
        0.83908738,  0.77545893,  0.24749326,  0.62086031,  0.28349209,
        0.22715005,  0.63059564,  0.91987631,  1.02895085,  1.16602283,
        0.65550519,  1.17263466,  0.33302167,  0.3296323 ,  0.37507063,
        0.65630232,  0.1512547 ,  0.86799947,  0.43641523,  0.90256971,
        0.46238665,  1.11861979,  0.95079278,  0.8472165 ,  0.42290289,
        0.36747644,  0.82557088,  1.06562807,  0.00678196,  1.10683636,
        1.13408506,  0.82153016,  0.80029938,  0.61173406,  1.04906567,
        0.62975082,  1.11243629,  0.12331919,  1.33714522,  0.62308409,
        0.87827162,  0.81969231,  0.77534234,  1.07304659,  0.85661786,
        0.20642722,  0.68979762,  0.80037715,  0.98984319,  0.79274826,
        1.20492386,  0.19595583,  0.96577074,  0.82487071,  0.9800842 ,
        0.89247466,  1.27062802,  0.78835457,  0.85501587,  0.06134381,
        0.02200337,  0.58379315,  0.70098387,  0.67376065,  0.77885629,
        0.96905111,  0.19818751,  0.93265989,  0.79392735,  1.3769117 ,
        0.68523858,  1.17580279,  0.68430801,  1.18595056,  1.07915863,
        0.72862205,  0.26965115,  0.4513422 ,  0.69528512,  1.04779655,
        0.3973557 ,  0.788051  , -0.05682743,  0.81346722,  0.63616823,
        0.22402938,  0.79288832,  1.12103031,  0.60233783,  0.46685735,
        0.64225056,  0.87119521,  1.01822931,  0.73783833,  0.34177488,
        1.22067009,  0.10795277,  0.65005111,  1.04069389,  0.71466745,
        0.76001386,  0.83106084,  0.78972879,  1.22136273,  1.08657659,
        0.87113555,  0.58351672,  0.1310088 ,  0.91463046,  1.23859877,
        0.93465167,  0.04672715,  0.89529279,  0.98135578,  0.71618   ,
        0.16369983,  0.82758831,  0.72836152,  0.27830234,  0.67369468,
        0.703798  ,  0.17579103,  0.95698341,  0.90281599,  0.6813236 ,
        1.22212303,  0.46380583,  0.77226413,  0.85583005,  1.1636508 ,
        0.62833154,  0.99627565,  0.32828755,  0.78066015,  0.80612116,
        0.9432469 ,  0.56365868,  0.87748518,  0.65143212,  0.94288289,
        1.14259753,  0.86442249,  0.44872202,  1.07689227,  0.40961331,
        1.09596215,  0.51755166,  0.70941787,  0.69031244,  1.00399505,
        0.98436494])

In [120]:
y_train

5      1
135    1
122    1
167    0
85     1
      ..
106    1
14     1
92     1
179    1
102    1
Name: status, Length: 156, dtype: int64

# Intercept -> b

In [121]:
lin_reg_model.intercept_

np.float64(1.8211092776992457)

In [122]:
X_train.shape

(156, 22)

In [123]:
lin_reg_model.coef_

array([-2.93525393e-03, -2.48524451e-04, -1.54970117e-03, -2.83101929e+02,
       -3.10870464e+03,  1.23839345e+03,  5.49438876e+01, -2.73838477e+02,
        4.00335275e+01,  1.90561448e-01,  9.50545410e+03, -4.00805849e+01,
       -2.57726986e+00, -3.17675263e+03, -2.43582582e+00, -1.57860361e-02,
       -1.03408785e+00,  4.78060604e-01,  8.03097747e-02,  1.28214062e+00,
        1.01409452e-01,  1.75257346e+00])

### Optimization Algorithm

In [124]:
X_train.columns

Index(['MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Jitter(%)',
       'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ', 'Jitter:DDP',
       'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'RPDE', 'DFA', 'spread1',
       'spread2', 'D2', 'PPE'],
      dtype='object')

## Y = b + p1x1 + p2x2 + p3x3 + p4x4 +  .......... p24x24

In [125]:
print( 'Linear Regression Evaluation :' )
print( '-------------------------' )
print(  )

MAE_train = mean_absolute_error( y_train, y_pred_train_lr )
MAE_test = mean_absolute_error( y_test, y_pred_test_lr )

MSE_train = mean_squared_error( y_train, y_pred_train_lr )
MSE_test = mean_squared_error( y_test, y_pred_test_lr )

RMSE_train = root_mean_squared_error( y_train, y_pred_train_lr )
RMSE_test = root_mean_squared_error( y_test, y_pred_test_lr )

print( f'Mean Absolute Error of training : { MAE_train }' )
print( f'Mean Absolute Error of Testing : { MAE_test }' )

print(  )
print( f'Mean Squared Error of training : { MSE_train }' )
print( f'Mean Squared Error of Testing : { MSE_test }' )
print(  )
print( f'Root Mean Squared Error of Training : { RMSE_train }' )
print( f'Root Mean Squared Error of Testing : { RMSE_test }' )

Linear Regression Evaluation :
-------------------------

Mean Absolute Error of training : 0.23831598856875993
Mean Absolute Error of Testing : 0.2718603270315076

Mean Squared Error of training : 0.09085765172973165
Mean Squared Error of Testing : 0.12655291699726362

Root Mean Squared Error of Training : 0.3014260302789586
Root Mean Squared Error of Testing : 0.3557427680182179

### Model Serialization ( Saving ) ( Dumping )
#### Save to extension .pkl

In [126]:
import joblib
import pickle

In [127]:
lin_reg_model

LinearRegression()

In [128]:
 joblib.dump( lin_reg_model, '../Artifacts/parkinson_model.pkl' )

['../Artifacts/parkinson_model.pkl']

In [129]:
df.sample()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,MDVP:APQ,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
125,145.174,198.109,80.637,0.00733,0.00005,0.00414,0.00422,0.01242,0.02362,0.233,0.01235,0.01495,0.01944,0.03706,0.01874,18.857,1,0.637518,0.735546,-5.594275,0.12795,1.765957,0.222716

In [130]:
df.shape

(195, 23)

### Define a function to evaluate any regressor

In [52]:
#### model

<h3>Import a colorama library for styling the color of words and paragraphs

<h4> Fore Stands to foreground color

In [131]:
from colorama import Fore

In [132]:
print(  Fore.GREEN + 'hello' )

hello

In [133]:
def evaluate_regressor( model, model_name: str ,X_train, X_test, y_train, y_test  ) :
    
    print( 'Training.........' + '\n' )
    
    print( model_name + ':' )
    print( '-'*20 )
    
    model.fit( X_train, y_train ) # Training !
    y_pred_train = model.predict( X_train )
    y_pred_test = model.predict( X_test )

    print(  )

    MAE_train = mean_absolute_error( y_train, y_pred_train )
    MSE_train = mean_squared_error( y_train, y_pred_train )
    
    RMSE_train = root_mean_squared_error( y_train, y_pred_train )
    
    MAE_test = mean_absolute_error( y_test, y_pred_test )
    MSE_test = mean_squared_error( y_test, y_pred_test )
    RMSE_test = root_mean_squared_error( y_test, y_pred_test )

    print( f'Mean Absolute Error of training : { MAE_train }' )
    print( Fore.WHITE + f'Mean Absolute Error of Testing : { MAE_test }' )
    print(  )

    print( Fore.CYAN + f'Mean Squared Error of training : { MSE_train }' )
    print( Fore.RED  + f'Mean Squared Error of Testing : { MSE_test }' )
    print(  )

    print( Fore.WHITE + f'Root Mean Squared Error of Training : { RMSE_train }' )
    print( Fore.WHITE + f'Root Mean Squared Error of Testing : { RMSE_test }' )

## [1] KNN

In [134]:
knn_model = KNeighborsRegressor( n_neighbors=7 )

In [135]:
evaluate_regressor( knn_model, 'K Neighbors Regressor', X_train, X_test, y_train, y_test )

Training.........

K Neighbors Regressor:
--------------------

Mean Absolute Error of training : 0.16666666666666666
Mean Absolute Error of Testing : 0.24542124542124547

Mean Squared Error of training : 0.07692307692307693
Mean Squared Error of Testing : 0.1564625850340136

Root Mean Squared Error of Training : 0.2773500981126146
Root Mean Squared Error of Testing : 0.3955535172818131

## [2] Linear Regression

In [136]:
lin_reg_model = LinearRegression()

In [137]:
evaluate_regressor( lin_reg_model, 'Linear Regression without regularization', X_train, X_test, y_train, y_test  )

Training.........

Linear Regression without regularization:
--------------------

Mean Absolute Error of training : 0.23831598856875993
Mean Absolute Error of Testing : 0.2718603270315076

Mean Squared Error of training : 0.09085765172973165
Mean Squared Error of Testing : 0.12655291699726362

Root Mean Squared Error of Training : 0.3014260302789586
Root Mean Squared Error of Testing : 0.3557427680182179

## [3] Linear Regression with regularization L1 ( Lasso )

In [138]:
lin_reg_L1 = Lasso( alpha = 0.2 )

In [139]:
evaluate_regressor( lin_reg_L1, 'Linear Regression with REGULARIZATION ( L1 )', X_train, X_test, y_train, y_test )

Training.........

Linear Regression with REGULARIZATION ( L1 ):
--------------------

Mean Absolute Error of training : 0.2852969296585134
Mean Absolute Error of Testing : 0.2953688883200715

Mean Squared Error of training : 0.1334868225972206
Mean Squared Error of Testing : 0.1453222642162457

Root Mean Squared Error of Training : 0.36535848504889085
Root Mean Squared Error of Testing : 0.3812115740848456

## [4] Linear Regression with regularization L2 ( Ridge )

In [140]:
ridge = Ridge(  )

In [141]:
ridge.fit(X_train, y_train)

Ridge()

In [142]:
ridge.coef_

array([-1.82960275e-03, -6.88033476e-04, -1.40058635e-03, -1.71076083e-02,
       -1.34086225e-04, -6.76856693e-03, -7.67268631e-03, -2.03204191e-02,
        2.33614482e-03, -1.44278817e-02,  7.21661807e-04, -7.64493120e-04,
       -1.06867699e-03,  2.12134380e-03, -1.47568987e-01, -1.43067320e-03,
       -2.53550169e-01,  1.63566397e-01,  1.27338661e-01,  1.71333121e-01,
        2.62989094e-01,  3.07452120e-03])

In [143]:
evaluate_regressor( ridge, 'Linear Regression with REGULARIZATION ( L2 )', X_train, X_test, y_train, y_test)

Training.........

Linear Regression with REGULARIZATION ( L2 ):
--------------------

Mean Absolute Error of training : 0.26437143072856867
Mean Absolute Error of Testing : 0.2722172347663172

Mean Squared Error of training : 0.1100817877148107
Mean Squared Error of Testing : 0.11848003490312466

Root Mean Squared Error of Training : 0.33178575574429153
Root Mean Squared Error of Testing : 0.344209289391098

## [5] Support Vector Machine

In [144]:
from sklearn.svm import SVR

In [145]:
svm_regressor = SVR(  )

In [146]:
evaluate_regressor( svm_regressor, 'SVM', X_train, X_test, y_train, y_test  )

Training.........

SVM:
--------------------

Mean Absolute Error of training : 0.2305210177196743
Mean Absolute Error of Testing : 0.21819225439431306

Mean Squared Error of training : 0.13774651117966985
Mean Squared Error of Testing : 0.13025168122972103

Root Mean Squared Error of Training : 0.37114217111461456
Root Mean Squared Error of Testing : 0.36090397785244904

## [6] Support Vector Machine with Scaling

In [147]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

In [148]:
svm_pipeline = make_pipeline(StandardScaler(), SVR())

In [149]:
svm_pipeline

Pipeline(steps=[('standardscaler', StandardScaler()), ('svr', SVR())])

In [150]:
import joblib
import pickle

In [164]:
joblib.dump(svm_pipeline, '../Artifacts/svm_pipeline.pkl')

['../Artifacts/svm_pipeline.pkl']

In [152]:
evaluate_regressor( svm_pipeline, 'SVM With Scaling', X_train, X_test, y_train, y_test)

Training.........

SVM With Scaling:
--------------------

Mean Absolute Error of training : 0.15491144457757322
Mean Absolute Error of Testing : 0.17652892886724547

Mean Squared Error of training : 0.06098080804675313
Mean Squared Error of Testing : 0.07287486387794075

Root Mean Squared Error of Training : 0.24694292467441364
Root Mean Squared Error of Testing : 0.2699534476126222

### Try Fine-Tuning

<h3> if kernel == 'poly' --> higher degree --> pruning overfitting

<h3>if gamma small -->Try not to fit all data --> high error --> underfitting
<h3> if gamma high --> FIT all the data as possible --> low error --> Overfitting

In [75]:
#### C ---> Regularization Parameter 
#### High C ---> Model tries hard to fit all data --> risk overfitting
### Low C --> Model allows errors --> risk underfitting

<hr>

In [160]:
svm_model=SVR(gamma=0.2, C=0.5)

In [161]:
gs_svm=GridSearchCV(
    svm_regressor,
    param_grid={
    'gamma':[0.2,0.4,0.5,0.7],
    'C':[0.2,0.4,0.5,0.7]
    })

<h3> Train X and Y for all combinations
<h4> Takes much time around 10-15 mins

In [162]:
gs_svm.fit(X_train,y_train)

GridSearchCV(estimator=SVR(),
             param_grid={'C': [0.2, 0.4, 0.5, 0.7],
                         'gamma': [0.2, 0.4, 0.5, 0.7]})

In [163]:
gs_svm.best_params_

{'C': 0.4, 'gamma': 0.2}